name: Setup Build Environment
description: Sets up Java, Android and Gradle for build

runs:
  using: 'composite'
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4.8.0
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: Set up Android
      uses: android-actions/setup-android@07976c6290703d34c16d382cb36445f98bb43b1f # v3.2.1

    - name: Make gradlew executable
      shell: bash
      run: chmod +x ./gradlew

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808  # v4.1.0

    - run: ./gradlew androidDependencies
      shell: bash
#    - uses: gradle/wrapper-validation-action@56b90f209b02bf6d1deae490e9ef18b21a389cd4 # pin@1.1.0
