// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.kotlin.android) apply false
    alias(libs.plugins.kotlin.compose) apply false
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.kotlin.parcelize) apply false
    alias(libs.plugins.detekt) apply false
    id 'io.github.gradle-nexus.publish-plugin' version '2.0.0'
}

configure(project(':universal_components')) {
    apply plugin: 'io.gitlab.arturbosch.detekt'

    detekt {
        buildUponDefaultConfig = true
        config.setFrom(rootProject.files('config/detekt/detekt.yml'))
        parallel = true
        source.setFrom(files('src/main/java', 'src/main/kotlin', 'src/test/java', 'src/test/kotlin'))
    }

    tasks.withType(io.gitlab.arturbosch.detekt.Detekt).configureEach {
        jvmTarget = '17'
        reports {
            html.required.set(true)
            xml.required.set(true)
            sarif.required.set(true)
            txt.required.set(false)
        }
    }

    tasks.withType(io.gitlab.arturbosch.detekt.DetektCreateBaselineTask).configureEach {
        jvmTarget = '17'
    }

    dependencies {
        detektPlugins libs.detekt.formatting
    }
}

nexusPublishing {
    repositories {
        sonatype{
            nexusUrl.set(uri('https://ossrh-staging-api.central.sonatype.com/service/local/'))
            snapshotRepositoryUrl.set(uri('https://central.sonatype.com/repository/maven-snapshots/'))
            username.set(System.getenv("MAVEN_USERNAME"))
            password.set(System.getenv("MAVEN_PASSWORD"))
        }
    }
}