name: Detekt

on:
  merge_group:
  workflow_dispatch:
  push:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  detekt:
    name: Detekt
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup build environment
        uses: ./.github/actions/setup

      - name: Run Detekt
        run: ./gradlew detekt --continue --console=plain --no-daemon